# Generated by Django 5.1.5 on 2025-03-29 12:01

import django.db.models.deletion
import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'vehicle_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Vehicle Title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Uploaded At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.category')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicle',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Variant Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('image_category', models.CharField(choices=[('practical', 'Practical'), ('executive', 'Executive'), ('performance', 'Performance')], max_length=20, verbose_name='Image Category')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to=vehicles.models.vehicle_image_upload_path, verbose_name='Variant Image')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variants',
                'db_table': 'vehicle_variant',
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(fields=('vehicle', 'color', 'image_category'), name='unique_vehicle_variant')],
            },
        ),
        migrations.CreateModel(
            name='VehiclePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_type', models.CharField(choices=[('base', 'Base Model'), ('top', 'Top Model'), ('standard', 'Standard')], default='standard', max_length=10, verbose_name='Specification Type')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'vehicle_price',
                'constraints': [models.UniqueConstraint(fields=('vehicle', 'spec_type', 'color'), name='unique_vehicle_price')],
            },
        ),
    ]
