# Generated by Django 5.1.5 on 2025-03-29 12:01

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=content.models.showroom_image_upload_path, verbose_name='Showroom Image'),
        ),
    ]
